distributed:
  distributed_no_spawn: True
  distributed_world_size: 1
  distributed_backend: nccl
  ddp_backend: c10d
  device_id: 0
  distributed_rank: 0
  bucket_cap_mb: 25
  distributed_port: 10010
  distributed_init_method: placeholder
